# Generated by Django 6.0 on 2025-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='user_type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student'), ('UNDEFINED', 'Undefined')], default='Undefined', max_length=50),
        ),
    ]
