# Generated by Django 6.0 on 2025-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accountuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='user_type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student'), ('GUARDIAN', 'Guardian'), ('UNDEFINED', 'Undefined')], default='Undefined', max_length=50),
        ),
    ]
