# Generated by Django 6.0 on 2026-01-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudentrelationship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelationship',
            unique_together={('parent', 'student')},
        ),
    ]
