# Generated by Django 6.0 on 2026-01-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/parents/'),
        ),
    ]
