# Generated by Django 6.0 on 2026-01-11 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_parentprofile_photo'),
        ('student', '0004_studentprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInvitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invited_first_name', models.CharField(blank=True, max_length=255)),
                ('invited_last_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Personal message to include in invitation')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to='parent.parentprofile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='parent.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invitations', to='student.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='parent_pare_token_d8643a_idx'), models.Index(fields=['invited_email', 'status'], name='parent_pare_invited_04d39a_idx')],
            },
        ),
    ]
