# Generated by Django 6.0 on 2026-01-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_trip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/students/'),
        ),
    ]
